### ISSUE TITLE
Will the `develop` branch have a `Parse()` function too?

### ISSUE THREAD

**Issue by mholt** [evanoberholster/imagemeta#47]
Hi, I'm dipping my toes back into this library, which I'm really looking forward to (the `develop` branch).

I notice the README for v1 shows a function, `imagemeta.Parse()`. Will or does the develop branch have something like this too?

Basically, "here's a file, parse out all the metadata you can find, whatever the format."

That would make this an absolute dream. :sun_behind_small_cloud:

Thanks for working on this lib!

PS. Will there be a way to iterate all metadata fields/values? I know currently there's a lot of getter methods, but do you think we will be able to enumerate them all? Even if they're uncommon I'd like to access whatever is in there.

**Comment by evanoberholster** [comment]
Hi. Thanks for coming back to this library. I am actively working on the ```develop``` branch. Since there are so many changes it will replace the current ```main``` branch.

There will be a similar function to ```imagemeta.Parse(io.Reader)```. The develop branch has this function but I believe it can be refined and clarified. Do you have any suggestions?

I am working on a function to iterate all metadata tags and their values. It may potentially be less efficient but hope to include it.

**Comment by mholt** [comment]
Perfect. Sounds great for my use case.

This is my wishlist:

- A function that can parse any/all metadata out of a file (any common formats)
    - _This doesn't have to be 100% comprehensive -- for example, we talked about Maker Notes before, and how they're proprietary; you don't need to decode those, but if you can still parse the value out, that'd be awesome, even if this lib doesn't interpret them._
- A way to read any/all metadata that was parsed
    - _I understand there are a ton of fields. If I can somehow access their values easily in my own code, that'd be great -- ideally as string, int, or whatever basic type it may be._
    - _Helper methods for the most common data would be nice to have. For example, a getter for `DateTime()` or `LatLon()` that can know the variety of ways that data is stored, so I don't have to. Those two are the big ones for me._
- Efficient is great, but correctness and completeness is more important to me. I would be OK with sacrificing some efficiency to get access to more/all metadata, for example.

Anyway, your lib totally fits the bill. That's all I have for feedback right now. :+1: Let me know how else I can help!

**Comment by evanoberholster** [comment]
- Makernotes: I would like to add these in as soon as the basics are well developed. As you mention, there is variety of data and each Make/Model may be slightly different. 
- Custom Tag Parsing: Take a look at 5fb96b9. Does this fit what you are looking for? It can still do with some polishing.
-  Precision / Completeness / Efficiency: I agree priority should be in this order.  

Ideas are a great help, will appreciate PRs as soon as I can push ```develop``` to ```main```.

**Comment by mholt** [comment]
@evanoberholster Awesome! I am excited to try it out. I see your PR in progress. I'll try to clone it down soon and let you know how it goes.

**Comment by mholt** [comment]
I believe my request was fulfilled by the `imagemeta.Decode()` function now. Thank you!
