### ISSUE TITLE
Support for Dublin Core namespaces XMP tags?

### ISSUE THREAD

**Issue by adampresley** [evanoberholster/imagemeta#60]
Hello. I did a quick test using this library and I'm liking what I'm seeing thus far. I am wondering if you have any plans to support additional XMP namespaces, like Dublin Core (https://developer.adobe.com/xmp/docs/XMPNamespaces/dc/)?  A lot of photos I have store keywords, which in a lot of cases are stored in both IPTC Keywords and XMP Subject. The XMP Subject appears to be using the <dc:subject> tag as seen in the screenshots below.

![CleanShot 2024-12-03 at 16 25 18@2x](https://github.com/user-attachments/assets/9ba5bba0-230f-4496-8c42-16ec1fb703ba)

![CleanShot 2024-12-03 at 16 27 00@2x](https://github.com/user-attachments/assets/03ded278-2565-4048-b89e-0833d28d1572)

**Comment by evanoberholster** [comment]
Hi @adampresley, I would be open to a pull request if you would like to help develop it. Unfortunately I don't have the time to add that on right now. It shouldn't be hard. Just requires reading through the library.

Thanks for asking.
